#!/bin/sh

PID="org.webosinternals.lumberjack"

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Stop the service if running
/sbin/stop ${PID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${PID}

# Remove the executable
rm -f /var/usr/sbin/${PID}

exit 0
